//
//  ConstantCollection.swift
//  TravelEasy
//
//  Created by 张晓飞 on 16/8/10.
//  Copyright © 2016年 张晓飞. All rights reserved.
//

import UIKit

let FONTCOLOR = "222222"
let FONTSECCOLOR = "aaaaaa"

let NAVIGATIONBARTINTCOLOR = "0078C9"
let BACKGROUNDCOLOR = "F5F5F5"

let LINECOLOR = "E0E1E2"
let TEXTCOLOR = "FF6600"

let FONT1 : CGFloat = 18
let FONT2 : CGFloat = 15
let FONT3 : CGFloat = 13
let FONT4 : CGFloat = 12
let FONT5 : CGFloat = 11

let SCREENWIDTH = UIScreen.main.bounds.size.width
let SCREENHEIGHT = UIScreen.main.bounds.size.height

let BUTTONBGCOLORNORMAL = "0071C4"
let BUTTONBGCOLORHIGHLIGHT = "095B90"
let BUTTONBGCOLORDISABLE = "C6E5FF"

let BUTTON2BGCOLORNORMAL = "FFFFFF"
let BUTTON2BGCOLORHIGHLIGHT = "0071C4"
let BUTTON2BGCOLORDISABLE = "FFFFFF"

let BUTTON3BGCOLORNORMAL = "FF6600"
let BUTTON3BGCOLORHIGHLIGHT = "D84507"
let BUTTON3BGCOLORDISABLE = "F69B63"
